export const GET_POSTS = "GET_POSTS";
export const CREATE_POST = "CREATE_POST";
export const UPDATE_POST = "UPDATE_POST";
export const DELETE_POST = "DELETE_POST";
export const SELECTED_POST = "SELECTED_POST";
export const IS_EDIT_ACTIVE = "IS_EDIT_ACTIVE";
export const IS_CONFIRMATION_ACTIVE = "IS_CONFIRMATION_ACTIVE";
